services:
  postgres:
    image: postgres:15
    container_name: biblioteca_postgres
    environment:
      POSTGRES_USER: biblioteca_user
      POSTGRES_PASSWORD: biblioteca_pass
      POSTGRES_DB: biblioteca_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: